//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatMaster
    {
        public long ChatMasterId { get; set; }
        public long UserMasterId { get; set; }
        public string Message { get; set; }
        public long ProjectId { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual UserMaster UserMaster { get; set; }
    }
}
