//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long LinkId { get; set; }
        public long ModuleId { get; set; }
        public string LinkName { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> ViewIndex { get; set; }
        public bool IsDefault { get; set; }
        public bool IsSingle { get; set; }
        public long CreatedById { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
        public Nullable<bool> IsVisible { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
