//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Project()
        {
            this.ChatMasters = new HashSet<ChatMaster>();
            this.CommentMasters = new HashSet<CommentMaster>();
            this.ProjectAssignies = new HashSet<ProjectAssigny>();
            this.ProjectAttachments = new HashSet<ProjectAttachment>();
            this.TaskMasters = new HashSet<TaskMaster>();
            this.TimeTrackers = new HashSet<TimeTracker>();
        }
    
        public long ProjectId { get; set; }
        public string TagLine { get; set; }
        public string Name { get; set; }
        public string ClientName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Budget { get; set; }
        public string BasicDescription { get; set; }
        public string ConfidentialDescription { get; set; }
        public Nullable<int> EstimateHours { get; set; }
        public Nullable<int> TeamMemberCount { get; set; }
        public Nullable<int> ActualTeamMemberCount { get; set; }
        public Nullable<long> ProjectStatusMasterId { get; set; }
        public string LiveURL { get; set; }
        public string StagingURL { get; set; }
        public bool IsActive { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedDateInt { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMaster> ChatMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentMaster> CommentMasters { get; set; }
        public virtual ProjectStatusMaster ProjectStatusMaster { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAssigny> ProjectAssignies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectAttachment> ProjectAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskMaster> TaskMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeTracker> TimeTrackers { get; set; }
    }
}
