//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Activity
    {
        public long ActivityId { get; set; }
        public string UserId { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public Nullable<long> TaskMasterId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool IsOnDashboard { get; set; }
        public bool IsDelete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> CreatedDateInt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
